
services:
  server:
    build: ./Server
    ports:
      - "42069:42069"
    env_file:
      - .env
    networks:
      - waterways-network
    restart: unless-stopped

  client:
    build: ./WaterWays
    ports:
      - "5173:5173"
    env_file:
      - .env
    environment:
      - VITE_API_URL=http://192.168.50.166:42069
    depends_on:
      - server
    networks:
      - waterways-network
    restart: unless-stopped

networks:
  waterways-network:
    driver: bridge
